# Primer TP de Simulacion

## Grupo 2


### Alumnos:

- Duzac, Emilia
- Belletti, Gabriel Ignacio
- Vazquez, Nicolaz Alberto
- Cohen, Martin

### Generador de numeros aleatorio elegido

MIXMAX

## Ejercicio 1

Implementar generador de numeros aleatorios.
Sobre el generador de números al azar elegido, se pide:
- Implementarlo en función de la especificación del mismo.
- Modificarlo (si aplica) para obtener números al azar entre 0 y 1
- Realizar los gráficos que se consideren adecuados para mostrar las distribuciones de números pseudoaleatorios generados en ambos casos (explicar que se busca interpretar con cada uno de los gráficos)

In [2]:
import numpy as np
import matplotlib as plot

In [3]:
# Parameters defined in paper
N = 139 # Matrix and vector size
s = 0  # Magic number
p = 9223372036853751941 # Modulus

In [4]:
def generate_mixmax_matrix(size, magic_number):
    
    # Initialize the MIXMAX matrix with ones
    matrix = np.ones((size, size), dtype=int)
    
    # Fill the matrix with the specified pattern
    for i in range(size):
        for j in range(size):
            if i == j and j > 0:
                matrix[i][j] = 2
            elif j < i and j > 0:
                matrix[i][j] = (i + 1) - (j - 1)

    matrix[2][1] += magic_number

    return matrix

mixmax_matrix = generate_mixmax_matrix(N, s)

print(mixmax_matrix)

[[  1   1   1 ...   1   1   1]
 [  1   2   1 ...   1   1   1]
 [  1   3   2 ...   1   1   1]
 ...
 [  1 137 136 ...   2   1   1]
 [  1 138 137 ...   3   2   1]
 [  1 139 138 ...   4   3   2]]


In [5]:
def generate_initial_vector(seed, size, period):

    # Pseudo random vector from seed
    a = 6364136223846793005
    c = 1

    random_numbers = []
    x = seed
    for _ in range(size):
        x = ((a * x + c) % period) / period
        random_numbers.append(x)
    return random_numbers

initial_vector = generate_initial_vector(42, N, p)

print(initial_vector)

[0.9800433435344447, 0.6762309184326339, 0.46660003158132946, 0.32195450331717784, 0.2221489395423314, 0.15328299753945182, 0.10576542648857613, 0.07297825342586531, 0.050355070176595663, 0.03474505038772526, 0.023974120624037296, 0.016542167971612474, 0.011414112971746592, 0.007875749729743213, 0.005434275441209239, 0.0037496556625463934, 0.0025872662767600914, 0.0017852164009945818, 0.0012318011590097989, 0.0008499440709219034, 0.0005864622860689734, 0.00040465958261017026, 0.00027921552960522136, 0.0001926590035749344, 0.00013293491128866099, 9.17252259765311e-05, 6.329050058322302e-05, 4.3670510717519044e-05, 3.0132697462571237e-05, 2.0791592345784034e-05, 1.4346220175283925e-05, 9.898906726086216e-06, 6.830255856561613e-06, 4.712883589775955e-06, 3.2518945405891413e-06, 2.2438105889257357e-06, 1.5482316219465221e-06, 1.068281416901081e-06, 7.371152801164351e-07, 5.08610303975247e-07, 3.509416346232248e-07, 2.421500900580104e-07, 1.670838120363444e-07, 1.1528800273382801e-07, 7.954

In [12]:
class MixmaxRNG:

    def __init__(self, seed, size, magic_number, period):
        # crea la matriz
        self.matrix = generate_mixmax_matrix(size, magic_number)
        # crea el vector inicial (no se retornaran sus valores)
        self.vector = generate_initial_vector(seed, size, period)

    """generates a uniform pseudo random value between 0 and 1,
    you can add an interval (a, b) to return a value between a and b"""
    def generate_number(self, interval=(0,1)):
        # valor pseudo aleatorio
        result = self._generate_new_vector()[0]
        return self._to_interval(result, interval)

    """calculates a new vector of numbers and replaces the current one with the new one with mod 1"""
    def _generate_new_vector(self):
        # calculo el nuevo vector
        new_vector = np.matmul(self.matrix, self.vector)
        # actualizo el vector con mod 1
        self.vector = [i % 1 for i in new_vector]
        return self.vector

    def _to_interval(self, number, interval):
        # encuentro la escala para multiplicar el valor
        scale = interval[1] - interval[0]
        # retorno el valor por la escala trasladando el 0 al minimo del intervalo
        return (number * scale) + interval[0]
        
rng = MixmaxRNG(27, N, s, p)

In [13]:
print(rng.generate_number())
print(rng.generate_number())
print(rng.generate_number())
print(rng.generate_number())
print(rng.generate_number())
print(rng.generate_number())

0.03235471312338856
0.4190100954913163
0.711639974162992
0.1351429148544412
0.21260472294952137
0.6256004844718177


## Ejercicio 2

En este ejercicio se busca aplicar distintos test estadísticos vistos en la materia para evaluar tanto el
comportamiento del generador de números pseudoaleatorios elegido como el comportamiento de otro generador
implementado por otro grupo. El grupo al cual le deben evaluar el generador se encuentra en la planilla de grupos
en Drive.
Para esta tarea se debe solicitar al equipo asignado uno o más lotes de números generados de los tamaños que se
necesiten. El equipo que haya generado los números debe incluir en la notebook entregada el código utilizado
para generar los mismos.


a) Sobre los generadores implementados en el ejercicio 1:
- Proponer, y realizar, al menos 3 tests para evaluar su comportamiento.
- Evaluar e interpretar los resultados de cada test para distintos tamaños de muestras.


b) Sobre el generador implementado por el grupo asignado:
- Proponer, y realizar, al menos 3 tests para evaluar su comportamiento.
- Evaluar e interpretar los resultados de cada test para distintos tamaños de muestras.
- Comparar los resultados obtenidos para este generados con los obtenidos en el punto a)

## Ejercicio 3

Un uso posible de los satélites es la captura de imágenes, como se expone en
el trabajo:
Chen, W., Mackin, S., & Palmer, P. (2006). Performance Modelling of Imaging
Service of Earth Observation Satellites with Two-dimensional Markov Chain.
57th International Astronautical Congress. 10.2514/6.IAC-06-B5.3.05
Utilizando el generador del ejercicio 1, y los datasets provistos junto a este
enunciado, se pide:
- Reproducir la generación de localizaciones de imágenes al azar,
mostrada en la figura 5: “Distribution of targets over the globe” de la
sección 4. Resultados. En este caso las imágenes se generan de forma
uniformemente distribuida dentro de los parámetros de latitud y
longitud [−60◦,60◦] [−150◦, 150◦] , respectivamente.
- Modificar el método para sólo generar localizaciones de imágenes
dentro del continente australiano (figuras 22 y 23 del dataset). De aplicar, en función del método elegido,
calcular el factor de rendimiento de forma empírica.

## Ejercicio 4

Utilizando el generador de números pseudoaleatorios implementado en el ejercicio 1, y el trabajo
Li, Xiaomeng & li, Xingang & Wang, Jiangfeng. (2012). Using Cellular Automata to Investigate Pedestrian Conflicts
with Vehicles in Crosswalk at Signalized Intersection. Discrete Dynamics in Nature and Society. 2012.
10.1155/2012/287502.
Resolver:
- Simular al menos 2 escenarios planteados en el trabajo y comparar sus resultados.
- Proponer al menos 2 modificaciones a los escenarios planteados para peatones, autos, semáforos y
arterias de circulación, simularlas y comparar sus resultados.
- Realizar los gráficos que se consideren necesarios para mostrar los resultados
- Seleccionar un escenario de los simulados y realizar una animación utilizando los datos simulados

### Descripcion del escenario planteado:

Se utiliza un modelo de autómata celular para simular el tráfico.

Idealización del sistema físico en el que se supone que tanto el espacio como el tiempo son discretos y cada una de las unidades que
interactúan puede tener solo un número finito de estados discretos.
En los autómatas celulares el espacio se divide en muchas unidades, mediante métodos in-erráticos, cuadrícula con ciertas formas.
Cada unidad en la cuadrícula in-errática se llama celda, que solo puede tomar su valor en el conjunto de estados discretos limitados.
Todas las células siguen las mismas reglas de funcionamiento y dinámica discreta en la naturaleza y la sociedad.

Actualizar según las reglas parciales fijadas.
Un gran número de células constituyen la evolución del sistema dinámico mediante la simple interacción.
Los componentes más básicos de los autómatas celulares incluyen cuatro partes: celdas, espacio de celda, vecinos y reglas.
Además, también se debe incluir el estado de las celdas.

El modelo de autómata celular en el artículo se desarrolla para simular un cruce de peatones en una intersección señalizada con un
ciclo de tiempo de señal peatonal fijo de $90 s$.
La fase de la señal para peatones está diseñada en seis clases,
que tienen una duración de tiempo verde de $25 s$, $30 s$, $35 s$, $40 s$, $45 s$ y $50 s$, correspondientes a
$65 s$, $60 s$, $55 s$, $50 s$, $45 s$ y $40 s$ de duración del tiempo rojo, respectivamente.
El segmento de la carretera que conecta con la intersección está diseñado como carriles de dos vías para seis vehículos y
el ancho de cada carril es de 3,5 metros.
El ancho del paso de peatones también está diseñado en 6 clases, que son $2,5 m$, $3 m$, $3,5 m$, $4 m$, $4,5 m$ y $5 m$ con una longitud de cruce de $21 m$.
Además, se han establecido dos áreas de espera para peatones a ambos lados del paso de peatones con capacidad para 100 peatones como máximo cada vez.
En este modelo, el paso de peatones se divide en celdas cuadradas de $0,5 × 0,5 m^2$.
Cada celda está ocupada por un peatón o vacía. Las velocidades iniciales asignadas al peatón pueden ser 2, 3, 4, 5 o 6 celdas por segundo,
lo que representa que sus velocidades reales son $1 m/s$, $1,5 m/s$, $2 m/s$, $2,5 m/s$, y $3 $m/s$, respectivamente.
Las proporciones de los cinco tipos de velocidades se basan en los resultados de la observación de campo,
que comparten 27,3%, 52%, 13,7%, 4,8% y 2,2% respectivamente. A través de la comparación de la velocidad asignada y
el número de celdas vacías frontales verticales, cada peatón actualiza su velocidad en cada paso de tiempo.
Se supone que cada vehículo ocupa 6 × 5 celdas y su velocidad en el cruce de peatones es de $5 m/s$.

Generalmente, existen dos tipos de condiciones de contorno en los modelos de simulación de autómatas celulares:
la condición de contorno periódica y la condición de contorno abierto.
Por razones tanto prácticas como teóricas, las dos condiciones de contorno son preferibles en diferentes situaciones.

- En la condición de frontera periódica, los límites relativos están vinculados y se genera un estado estacionario invariante de traducción en el sistema.
- Por otro lado, la condición de límite abierto concuerda con una cierta probabilidad cuando se inserta y retira un vehículo de la celda límite,
en la que la invariancia traslacional se rompe, pero aún se pueden esperar estados estacionarios con un perfil de densidad no trivial.

En comparación con la condición de frontera periódica, la condición de frontera abierta es más realista y coherente para el modelo del artículo.
Por tanto, se adopta la condición de frontera abierta.

### Reglas del escenario planteado:

#### Celdas:

Cada celda mide 0.5 metros cuadrados ($0.5m × 0.5m$).

- Segmento de carretera: cuenta con dos carriles, para 6 vehiculos.
 - Carriles: ancho $3,5$ metros (7 celdas).
- Paso de peatones:
 - Ancho: posibles valores $2,5 m$, $3 m$, $3,5 m$, $4 m$, $4,5 m$ y $5 m$.
 - Largo: longitud de cruce de $21 m$, que corresponde a los 6 carriles de carretera ($3.5 × 6 = 21$).
- Un peaton solo ocupa 1 celda.
- Un vehiculo ocupa 6 × 5 celdas y su velocidad en el cruce de peatones es de $5 m/s$

#### Señales:

Total de periodo de semaforo 90 s (solo verde o rojo).
Fase de la señal para peatones (en segundos):

| Verde | Rojo |
|-------|------|
| 25    | 65   |
| 30    | 60   |
| 40    | 55   |
| 45    | 45   |
| 50    | 40   |

#### Movimiento:

Hay tres leyes básicas de movimiento en los modelos de autómatas celulares para describir el comportamiento de los peatones:

- movimiento lateral: representa el comportamiento de cambio de trayectoria de un peatón, cuyo resultado es obtener espacio de aceleración y evitar una colisión frontal.
- movimiento lineal: considera la velocidad de preferencia personal y otros peatones cercanos para identificar el número de pasos para avanzar.
- evitación de colisiones: se refiere al comportamiento de cómo evitar colisiones frontales entre peatones que caminan cerca uno del otro en dirección opuesta.

En la evolución de este modelo, tanto los peatones como los vehículos deben cumplir con las reglas de sus movimientos

#### Reglas para peatones:

Arribo, (es una distribucion Poisson).
$P_k = \frac{(λ_p)^{k}}{k!} × e^{-λt} = 0$

Donde:
- $P_k$ denota la probabilidad de alcanzar k peatones durante el intervalo de conteo t.
- $λ_p$ denota la tasa media de llegada de peatones cápita/segundo.
- $t$ denota cada intervalo de tiempo contado.

En la evolución de este modelo, los peatones dan prioridad a la celda frontal como destino.
El peatón puede avanzar en las celdas o cambiar a la izquierda o a la derecha cuando está bloqueado.

La velocidad inicial del peatón que ingresa al cruce de peatones $v_{i,j}$, se asigna de acuerdo con:
- 6 caso: $p > 0.978$
- 5 caso: $0.978 ≥ p > 0.93$
- 4 caso: $0.93 ≥ p > 0.793$
- 3 caso: $0.793 ≥ p > 0.273$
- 2 caso: $0.273 ≥ p ≥ 0$

Donde:
- $p$ es un número aleatorio entre 0 y 1.
- $v_{i,j}$ denota la velocidad del peatón cuya ubicación es $x_{i,j}$.

La dinámica discreta en la naturaleza y la sociedad La velocidad del peatón en el cruce de peatones durante la simulación
se actualiza sobre la base de $v_{i,j} = min(d_{i,j}, v_{i,j})$.
Donde:
- $d_{i,j}$ denota el número de celdas vacías entre el peatón objetivo y su peatón verticalmente frontal más cercano.
- $x_{i,j}$ denota la ubicación del peatón.
- $v_{i-n,j±1}$ denota la velocidad del peatón cuya ubicación es xi−n, j±1 y es el primero detrás de la celda xi, j±1. El número de celdas vacías entre ellas es n.

Debido a que varios peatones pueden competir por una celda vacía y cada celda puede estar vacía u ocupada exactamente por un peatón,
existirán conflictos entre peatones en la evolución del modelo. Si ocurren conflictos,
el sistema seleccionará un peatón para que ocupe la celda al azar con la misma probabilidad.
El peatón seleccionado se moverá al destino en el siguiente paso de tiempo y el peatón que no esté seleccionado permanecerá en su ubicación original.
Los peatones tienen que esperar en el área de espera una vez que llegan a la hora del semáforo en rojo y
se supone que todos los peatones siguen las reglas de tránsito sin ningún comportamiento intencional al pasar el semáforo en rojo.
El comportamiento de pasar el semáforo en rojo solo ocurre en los peatones que no han terminado de cruzar cuando termina el semáforo en verde.
Cuando comience la luz verde, comenzarán a cruzar a las velocidades asignadas y acelerarán a la velocidad máxima para completar el cruce
si la luz verde termina.

El modelo simplifica el proceso de conflicto entre peatones opuestos.
Los peatones en direcciones opuestas pueden cruzarse entre sí si su celda de destino está vacía; de lo contrario,
necesitarán ajustar sus velocidades o mantener su posición original.

#### Reglas para vehiculos:

La ley de llegada de los vehículos es la misma que la de los peatones,
que sigue de manera similar la distribución de Poisson. Su tasa de llegada es $λv$.

Cuando el semáforo para peatones está en rojo y no hay ningún peatón en el cruce de peatones,
los vehículos pueden cruzar por la intersección. De lo contrario, se enfrentarían a conflictos con los peatones.

#### Reglas para conflictos entre peatones y vehículos:

En el trabajo publicado, de acuerdo con la relación de ocupación temporal y espacial de los usuarios de la vía en la intersección,
los conflictos entre peatones y vehículos se clasifican en 4 áreas, en la que los conflictos entre peatones y vehículos se pueden diferenciar
en 4 tipos de la siguiente manera:

- Área 1: conflictos entre vehículos que giran a la derecha desde el interior de la intersección y peatones, asumiendo que se permite girar a la derecha en rojo en la aproximación.
- Área 2: conflictos entre vehículos que se mueven en línea recta o que giran a la izquierda desde el interior de la intersección y peatones que van a baja velocidad o aquellos que cruzan la calle al final de la luz verde, asumiendo que los vehículos no tienen comportamiento al pasar la luz roja.
- Área 3: conflictos entre vehículos del segmento que se mueven en línea recta o que giran a la izquierda y peatones con velocidad lenta o aquellos que cruzan la calle al final de la luz verde, asumiendo que los vehículos no tienen comportamiento de pasar la luz roja.
- Área 4: conflictos entre vehículos que giran a la derecha del segmento y peatones, asumiendo que se permite girar a la derecha en rojo en la aproximación.

Hay dos definiciones relacionadas con el conflicto involucradas en el trabajo publicado. Uno es el evento de conflicto entre peatones y vehículos,
y el otro es el retraso del conflicto de peatones.
En este estudio de simulación, un evento de conflicto entre vehículo y peatón en un cruce de peatones se define como la situación en la que,
para evitar una colisión con un peatón,
el vehículo deja de avanzar hacia las celdas que actualmente están ocupadas por al menos un peatón o que estarán ocupadas. por al menos un peatón.
La demora por conflicto de peatones significa el tiempo de parada durante el cual
los peatones se estancan en el cruce de peatones para evitar el paso de los vehículos cuando ocurre un conflicto.
Si se alivia el conflicto, los peatones podrán seguir cruzando. Las reglas de conflicto se asignan de la siguiente manera.

- Si la celda objetivo del peatón está ocupada por un vehículo, el vehículo tiene prioridad para cruzar. Del mismo modo, si la celda objetivo del vehículo está ocupada por peatones, se dará prioridad a los peatones.
- Si el peatón y el vehículo tienen la misma celda objetivo, lo que significa que sus próximos pasos se superponen, el sistema dará prioridad de paso a uno de ellos aleatoriamente con la misma probabilidad, es decir, 0,5.

### Codigo de resolucion

#### Constantes

In [10]:
# valores fijos definidos por las reglas

# tiempo maximo de periodo para el semaforo
TRAFFIC_LIGHT_TOTAL_TIME = 90
# lista de tiempos base que el semaforo está en verde
TRAFFIC_GREEN_LIGHT_BASE_TIME_POSSIBILITIES = (25, 30, 35, 40, 45, 50)
# valor de la velocidad inicial segun las posibilidades,
# ordenados segun su vínculo con la probabilidad
# la velocidad esta expresada en celdas/tiempo
PEDESTRIAN_INITIAL_VELOCITY_POSSIBILITIES = (6, 5, 4, 3, 2)
# valor de la probabilidad velocidad inicial segun las posibilidades
# (ordenados de mayor a menor)
PROBABILITY_PEDESTRIAN_INITIAL_VELOCITY_POSSIBILITIES = (0.978, 0.93, 0.793, 0.273, 0.0)
# probabilidad de prioriedad de movimiento del peaton ante un vehiculo
PROBABILITY_PEDESTRIAN_PRIORITY_BEFORE_VEHICLE = 0.5
# tamaño de vehiculo
VEHICLE_SIZE_BROAD = 5
VEHICLE_SIZE_LONG = 6
# velocidad de vehiculo (1 metro = 2 celdas)
# la velocidad esta expresada en celdas/tiempo
VEHICLE_SPEED = 10
# tamaño del carril
LANE_SIZE_BROAD = 7
# Posibles ancho del paso de peatones (1 metro = 2 celdas)
CROSSWALKS_WIDTH_POSSIBILITIES = (5, 6, 7, 8, 9, 10)
# el largo del paso de peatones son 21 metros que son 42 celdas que equivale a los 6 carriles
CROSSWALKS_LARGE_POSSIBILITIES = 42
# verificacion (por posibles cambios)
if CROSSWALKS_LARGE_POSSIBILITIES != LANE_SIZE_BROAD * 6:
    raise ValueError("el tamaño de los carriles y el largo de la senda peatonal no coinciden")

#### Tipos

In [ ]:
"""representation of the specific location of the board"""
class Cell:
    def __init__(self):
        self.content = None

    def is_empty(self):
        return self.content is None

In [ ]:
"""representation of the board where the simulation occurs"""
class Cross:
    def __init__(self, crosswalks_width):
        self.matriz = self._generate_matriz(crosswalks_width)

    def _generate_matriz(self, crosswalks_width):
        crosswalks = []
        for i in range(crosswalks_width):
            # representacion del camino recto que deberian seguir los peatones
            crosswalk = []
            for j in range(CROSSWALKS_LARGE_POSSIBILITIES):
                crosswalk.append(Cell)
            crosswalks.append(crosswalk)
        return crosswalks

    def get_distance_to_next_obstacle(self, initial_pos, rigth):
        # "rigth" hace referencia a la derecha desde la perspectiva del tablero
        # el equivalente (respecto al peaton) de "rigth" o "left" en este caso seria solo "forward"
        return 0

    def lateral_movement_allowed(self, initial_pos, rigth):
        # "rigth" hace referencia a la derecha desde la perspectiva del peaton
        # el equivalente (respecto al tablero) de "rigth" es arriba y de "left" abajo
        if rigth:
            new_pos = (initial_pos[0] + 1, initial_pos[1])
        else:
            new_pos = (initial_pos[0] - 1, initial_pos[1])
        return self._get_pos(new_pos).is_empty()

    def _get_pos(self, pos):
        return self.matriz[pos[0], pos[1]]

In [ ]:
"""representation on the dashboard of a pedestrian"""
class Pedestrian:
    def __init__(self, pos):
        # posicion actual del peaton
        self.pos = pos
        # posicion tentativa (a trasladarse) del peaton
        self.attempt_pos = pos
        self.vel = 0

    def transfer(self):
        self.pos = self.attempt_pos

    def is_transferred(self):
        return self.pos == self.attempt_pos

In [ ]:
"""representation on the dashboard of a vehicle"""
class Vehicle:
    def __init__(self, cell):
        self.cell = cell
        self.vel = 0

#### Funciones

In [ ]:
"""receives a vector with pedestrians and a uniform random value between 0 and 1, returns a pedestrian"""
def pedestrian_selection_for_cell(pedestrians, val_p):
    # caso donde el valor inicial era 1
    if val_p == 1.0:
        return pedestrians[-1]
    # obtengo la cantidad de peatones que compiten por la celda
    cant = len(pedestrians)
    # el valor aleatorio es entre 0 y 1 lo ultiplico por la cantidad
    # asi obtengo un valor aleatorio entre 0 y la cantidad
    # se le aplica int para eliminar los decimales
    random_pos = int(val_p * cant)
    return pedestrians[random_pos]

"""Test of pedestrian_initial_velocity"""
def test_pedestrian_selection_for_cell():
    vec = (0, 1, 2, 3, 4)
    val = pedestrian_selection_for_cell(vec, 0.0) == 0
    val &= pedestrian_selection_for_cell(vec, 1.0) == 4
    val &= pedestrian_selection_for_cell(vec, 0.2) == 1
    val &= pedestrian_selection_for_cell(vec, 0.4) == 2
    val &= pedestrian_selection_for_cell(vec, 0.6) == 3
    val &= pedestrian_selection_for_cell(vec, 0.8) == 4
    val &= pedestrian_selection_for_cell(vec, 0.19) == 0
    val &= pedestrian_selection_for_cell(vec, 0.39) == 1
    val &= pedestrian_selection_for_cell(vec, 0.59) == 2
    val &= pedestrian_selection_for_cell(vec, 0.79) == 3
    if val:
        print("OK")
    else:
        print("ERROR")

test_pedestrian_selection_for_cell()

In [ ]:
"""receives a random value between 0 and 1, uses that value to know if the pedestrian has priority over a vehicle competing for the same cell, returns true if the pedestrian has priority"""
def pedestrian_priority_before_vehicle(vel_p):
    return vel_p < PROBABILITY_PEDESTRIAN_PRIORITY_BEFORE_VEHICLE

In [5]:
def traffic_light_times(n):
    types_traffic_green_light_base_time = TRAFFIC_GREEN_LIGHT_BASE_TIME_POSSIBILITIES
    if n > len(types_traffic_green_light_base_time) or n < 0:
        raise ValueError("Not exist traffic light base time type. Existing types 0 to " + str(len(types_traffic_green_light_base_time)) + ". wrong type entered: " + n)
    green_time = types_traffic_green_light_base_time[n]
    red_time = TRAFFIC_LIGHT_TOTAL_TIME - green_time
    return red_time, green_time

In [ ]:
"""given a random value and two vectors, one of values ordered from highest to lowest and another of results.
It will return the equivalent of the results according to the largest number in the vector to which the random value is greater."""
def get_discrete_value_according_to_probability(val_p, interval, vec):
    # caso nulo retorna el ultimo valor
    if val_p == 0.0:
        return vec[-1]
    # verifica que sea mayor al numero del vector
    # (el vector empieza ordenado como pre condicion)
    for i in range(len(interval)):
        if val_p > interval[i]:
            return vec[i]

"""given a random value it will return The initial speed of the pedestrian entering the crosswalk,
according to the previous rules."""
def pedestrian_initial_velocity(val_p):
    # valor de la velocidad segun las reglas
    vec = PEDESTRIAN_INITIAL_VELOCITY_POSSIBILITIES
    # probabilidad del valor de la velocidad segun las reglas
    interval = PROBABILITY_PEDESTRIAN_INITIAL_VELOCITY_POSSIBILITIES
    return get_discrete_value_according_to_probability(val_p, interval, vec)

"""Test of pedestrian_initial_velocity"""
def test_pedestrian_initial_velocity():
    val = pedestrian_initial_velocity(1.0) == 6
    val &= pedestrian_initial_velocity(0.979) == 6
    val &= pedestrian_initial_velocity(0.978) == 5
    val &= pedestrian_initial_velocity(0.931) == 5
    val &= pedestrian_initial_velocity(0.930) == 4
    val &= pedestrian_initial_velocity(0.794) == 4
    val &= pedestrian_initial_velocity(0.793) == 3
    val &= pedestrian_initial_velocity(0.274) == 3
    val &= pedestrian_initial_velocity(0.273) == 2
    val &= pedestrian_initial_velocity(0.001) == 2
    val &= pedestrian_initial_velocity(0.0) == 2
    if val:
        print("OK")
    else:
        print("ERROR")

test_pedestrian_initial_velocity()