In [3]:
import numpy as np

In [2]:
# Parameters defined in paper
N = 139 # Matrix and vector size
s = 0  # Magic number
p = 9223372036853751941 # Modulus

In [6]:
def generate_mixmax_matrix():
    
    # Initialize the MIXMAX matrix with zeros
    matrix = np.zeros((N, N), dtype=int)
    
    # Fill the matrix with the specified pattern
    for i in range(N):
        for j in range(N):
            if j == 0:
                matrix[i][j] = 1
            elif i == j and j > 0:
                matrix[i][j] = 2
            elif j < i:
                matrix[i][j] = (i + 1) - (j - 1)
            elif i < j:
                matrix[i][j] = 1
    
    # Add magic number
    matrix[2][1] += s

    return matrix

mixmax_matrix = generate_mixmax_matrix()

print(mixmax_matrix)

[[  1   1   1 ...   1   1   1]
 [  1   2   1 ...   1   1   1]
 [  1   3   2 ...   1   1   1]
 ...
 [  1 137 136 ...   2   1   1]
 [  1 138 137 ...   3   2   1]
 [  1 139 138 ...   4   3   2]]


In [7]:
def generate_initial_vector(seed):

    # Pseudo random vector from seed
    a = 6364136223846793005
    c = 1

    random_numbers = []
    x = seed
    for _ in range(N):
        x = (a * x + c) % p
        random_numbers.append(x)
    return random_numbers

initial_vector = generate_initial_vector(42)

print(initial_vector)

[9039304369660251863, 4469959833728060563, 5114085947924390389, 3891057922222447022, 5360099505877225315, 570778789714610640, 8714590074699650279, 689988557204763970, 6644787058748961420, 8858834791180401664, 3739536117488504594, 2552004962658648729, 3292727948760099646, 3783900734100335078, 2940326901464522198, 1422014648895486543, 5425485029846817099, 8072923204814552729, 8967524266553333918, 5015072680739994109, 4743386994743874862, 2904661173019649094, 4296199077387276578, 6403557198786587920, 7287930626553602591, 7745821675879376759, 1097762816338955161, 2989665147577335842, 6085075953957992558, 5538167378460860450, 1482132691273190126, 758635989760126335, 7546632487371006509, 7156902430148451722, 424131874229706581, 7453756450051766975, 3635036752377466765, 6919604506909327662, 6637596011608047101, 6276182788691353748, 7483928037242064867, 6673730653211040181, 2301996199894393528, 326745897085310582, 1174893146598356422, 2424235004229926512, 6309975518443994124, 30798814487702854