# Primer TP de Simulacion

## Grupo 2


### Alumnos:
Duzac, Emilia
Belletti, Gabriel Ignacio
Vazquez, Nicolaz Alberto
Cohen, Martin

### Generador de numeros aleatorio elegido

MIXMAX

## Ejercicio 1

Implementar generador de numeros aleatorios.
Sobre el generador de números al azar elegido, se pide:
- Implementarlo en función de la especificación del mismo.
- Modificarlo (si aplica) para obtener números al azar entre 0 y 1
- Realizar los gráficos que se consideren adecuados para mostrar las distribuciones de números pseudoaleatorios generados en ambos casos (explicar que se busca interpretar con cada uno de los gráficos)

In [5]:
import numpy as np

In [6]:
# Parameters defined in paper
N = 139 # Matrix and vector size
s = 0  # Magic number
p = 9223372036853751941 # Modulus

In [8]:
def generate_mixmax_matrix():
    
    # Initialize the MIXMAX matrix with zeros
    matrix = np.ones((N, N), 1, dtype=int)
    
    # Fill the matrix with the specified pattern
    for i in range(N):
        for j in range(N):
            if i == j and j > 0:
                matrix[i][j] = 2
            elif j < i and j > 0:
                matrix[i][j] = (i + 1) - (j - 1)
    # Add magic number
    matrix[2][1] += s

    return matrix

mixmax_matrix = generate_mixmax_matrix()

print(mixmax_matrix)

[[  1   1   1 ...   1   1   1]
 [  1   2   1 ...   1   1   1]
 [  1   3   2 ...   1   1   1]
 ...
 [  1 137 136 ...   2   1   1]
 [  1 138 137 ...   3   2   1]
 [  1 139 138 ...   4   3   2]]


In [9]:
def generate_initial_vector(seed):

    # Pseudo random vector from seed
    a = 6364136223846793005
    c = 1

    random_numbers = []
    x = seed
    for _ in range(N):
        x = ((a * x + c) % p) / p
        random_numbers.append(x)
    return random_numbers

initial_vector = generate_initial_vector(42)

print(initial_vector)

[0.9800433435344447, 0.6762309184326339, 0.46660003158132946, 0.32195450331717784, 0.2221489395423314, 0.15328299753945182, 0.10576542648857613, 0.07297825342586531, 0.050355070176595663, 0.03474505038772526, 0.023974120624037296, 0.016542167971612474, 0.011414112971746592, 0.007875749729743213, 0.005434275441209239, 0.0037496556625463934, 0.0025872662767600914, 0.0017852164009945818, 0.0012318011590097989, 0.0008499440709219034, 0.0005864622860689734, 0.00040465958261017026, 0.00027921552960522136, 0.0001926590035749344, 0.00013293491128866099, 9.17252259765311e-05, 6.329050058322302e-05, 4.3670510717519044e-05, 3.0132697462571237e-05, 2.0791592345784034e-05, 1.4346220175283925e-05, 9.898906726086216e-06, 6.830255856561613e-06, 4.712883589775955e-06, 3.2518945405891413e-06, 2.2438105889257357e-06, 1.5482316219465221e-06, 1.068281416901081e-06, 7.371152801164351e-07, 5.08610303975247e-07, 3.509416346232248e-07, 2.421500900580104e-07, 1.670838120363444e-07, 1.1528800273382801e-07, 7.954

## Ejercicio 2

En este ejercicio se busca aplicar distintos test estadísticos vistos en la materia para evaluar tanto el
comportamiento del generador de números pseudoaleatorios elegido como el comportamiento de otro generador
implementado por otro grupo. El grupo al cual le deben evaluar el generador se encuentra en la planilla de grupos
en Drive.
Para esta tarea se debe solicitar al equipo asignado uno o más lotes de números generados de los tamaños que se
necesiten. El equipo que haya generado los números debe incluir en la notebook entregada el código utilizado
para generar los mismos.


a) Sobre los generadores implementados en el ejercicio 1:
- Proponer, y realizar, al menos 3 tests para evaluar su comportamiento.
- Evaluar e interpretar los resultados de cada test para distintos tamaños de muestras.


b) Sobre el generador implementado por el grupo asignado:
- Proponer, y realizar, al menos 3 tests para evaluar su comportamiento.
- Evaluar e interpretar los resultados de cada test para distintos tamaños de muestras.
- Comparar los resultados obtenidos para este generados con los obtenidos en el punto a)

## Ejercicio 3

Un uso posible de los satélites es la captura de imágenes, como se expone en
el trabajo:
Chen, W., Mackin, S., & Palmer, P. (2006). Performance Modelling of Imaging
Service of Earth Observation Satellites with Two-dimensional Markov Chain.
57th International Astronautical Congress. 10.2514/6.IAC-06-B5.3.05
Utilizando el generador del ejercicio 1, y los datasets provistos junto a este
enunciado, se pide:
- Reproducir la generación de localizaciones de imágenes al azar,
mostrada en la figura 5: “Distribution of targets over the globe” de la
sección 4. Resultados. En este caso las imágenes se generan de forma
uniformemente distribuida dentro de los parámetros de latitud y
longitud [−60◦,60◦] [−150◦, 150◦] , respectivamente.
- Modificar el método para sólo generar localizaciones de imágenes
dentro del continente australiano (figuras 22 y 23 del dataset). De aplicar, en función del método elegido,
calcular el factor de rendimiento de forma empírica.

## Ejercicio 4

Utilizando el generador de números pseudoaleatorios implementado en el ejercicio 1, y el trabajo
Li, Xiaomeng & li, Xingang & Wang, Jiangfeng. (2012). Using Cellular Automata to Investigate Pedestrian Conflicts
with Vehicles in Crosswalk at Signalized Intersection. Discrete Dynamics in Nature and Society. 2012.
10.1155/2012/287502.
Resolver:
- Simular al menos 2 escenarios planteados en el trabajo y comparar sus resultados.
- Proponer al menos 2 modificaciones a los escenarios planteados para peatones, autos, semáforos y
arterias de circulación, simularlas y comparar sus resultados.
- Realizar los gráficos que se consideren necesarios para mostrar los resultados
- Seleccionar un escenario de los simulados y realizar una animación utilizando los datos simulados